style.css

https://github.com/theiaconf/monochrome-pro/issues/6

changed speakers to grid layout https://github.com/theiaconf/monochrome-pro/issues/6

---

style.css

Reverts theiaconf/monochrome-pro#9

Changed speakers to grid layout

---

page_about.php
page_engage.php
page_present.php
page_program.php
page_register.php
page_sponsor.php

Adding templates for sections to support banner styling including About, Engage, Present, Program, Register, and Sponsor templates.

Adding Section Templates

---

style-front.css
style.css

Adjust typography for global navgation
Remove old fonts from web site
Fix disappearing global nav on secondary pages
Updated mobile menu / secondary menu colors
(I don't know why this pull request is rewriting so much of what already exists =/)

Universal menu

---

banner.html
front-page.php
functions.php
page_about.php
page_engage.php
page_present.php
page_program.php
page_register.php
page_sponsor.php
style-front.css
style.css

Including most recent series of updates to bring main in line with new banners and other theme tweaks

Jgr 2021 11 16 session cards

---

page_dashboard.php
style.css

Adds a Dashboard banner page template and fixes a couple of minor bugs in the footer.

JGR 2021-12-16 Dashboard and Footer Fix

---

style.css

Need to revisit this but it is a short term fix to get Attend pages live

Adjust styling for ticket options

---

style.css

Add some formatting for Additional Times to get through IAC22 - can revisit in May

List additional times for sessions that recur

---

style.css

Merging this into main so that it unblocks @Chonathon and the work for Talks on Demand

Jgr 2022 01 14 program

---

style.css

Removing CSS to insert the word Program into program template pages.

Removing Breacrumb Hack CSS

---

style.css

Add new classes to handle placement of sessions with headshots - specifically for keynoters on the home page and IAC Dashboard

Keynote bios

---

style.css

JGR - 2022 02 17 cleanup

---

style.css

Changed orange to higher-contrast.

Jgr 2022 02 17 bug fixes

---

style.css

Lots of minor CSS updates for things like margin and padding and header logo positioning. Buttons now are spaced appropriately in the various ways I've seen them inserted into WP. Nav top-level items now have a hover state background color, which will hopefully make them seem more clickable.

JGR 2022 02 27 bug fixes

---

style.css

Fixes social media icon alignment on Dashboard.

JGR 2022 03 09 dashboard bug fix

---

style.css

Various CSS tweaks, including 404 page, utility links on program session cards, People of IAC pagination, icons for discord and gather on dashboard.

JGR 03 25 fixes

---

iac24_posters.php
style.css

Changes requested by co-chairs to help with styling all roles equally (posters, speakers, co-chairs, volunteers, etc)

Changes for rebecca

---

functions.php

Removes author name and URI from oEmbeds

Strip author name and URL from embeds in external sites

---

iac24_red_secondary.php
style.css

Add secondary template for logistics pages and others that relies on the same red color palate

Red template

---

style-front.css
style.css

Minor content tweaks for visuals

March updates
